### ISSUE TITLE
Roadmap api

### ISSUE THREAD

**Issue by sopyb** [NavigoLearn/API#3]
Edit side
- [x] Creatig a roadmap
- [x] Get roadmap info
  - [x] Full Roadmap info
  - [x] Mini Roadmap info (for search)
  - [x] Owner user profile
  - [x] Owner mini user profile
  - [x] Tags
- [x] Update roadmap info
  - [x] title
  - [x] description
  - [x] tags
  - [x] visibility
  - [x] owner
  - [x] data
- [x] Deleting a roadmap 
- [ ] #18
- [x] #17
- [ ] #5
- [x] #4
